### ISSUE TITLE
response.data() returns null

### ISSUE THREAD

**Issue by rajjys** [sealedtx/java-youtube-downloader#103]
`RequestVideoInfo request = new RequestVideoInfo(videoId);
Response<VideoInfo> response = downloader.getVideoInfo(request);
VideoInfo video = response.data(); /// response.data() is null`

Returns null hence can't retrieve videoInfo. I also was wondering if a Youtube API KEY is required for this to work

**Comment by sealedtx** [comment]
before calling `response.data()` you should check if request was successful -`response.ok()` 
if it returns `false` you can check what is returned by `response.error()`

**Comment by sealedtx** [comment]
`class java.lang.String cannot be converted to class java.lang.String`
seems very strange, may be you have some issues with java versions?

**Comment by rajjys** [comment]
`java.util.concurrent.ExecutionException: com.alibaba.fastjson2.JSONException:
 class java.lang.String cannot be converted to class java.lang.String

	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.github.kiulian.downloader.downloader.response.ResponseImpl.error(ResponseImpl.java:96)
	at MainClass.videoInfo(MainClass.java:70)
	at MainClass.main(MainClass.java:46)
Caused by: com.alibaba.fastjson2.JSONException: class java.lang.String cannot be converted to class java.lang.String

	at com.alibaba.fastjson.JSONArray.toJavaList(JSONArray.java:817)
	at com.github.kiulian.downloader.model.videos.VideoDetails.<init>(VideoDetails.java:30)
	at com.github.kiulian.downloader.parser.ParserImpl.parseVideoDetails(ParserImpl.java:182)
	at com.github.kiulian.downloader.parser.ParserImpl.parseVideoAndroid(ParserImpl.java:104)
	at com.github.kiulian.downloader.parser.ParserImpl.parseVideo(ParserImpl.java:63)
	at com.github.kiulian.downloader.parser.ParserImpl.lambda$0(ParserImpl.java:49)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

**Comment by rajjys** [comment]
Yeah, like you pointed before, i had a problem with my `classpath` and the overall project configuration.
 I reset everything and started from scratch, now it works fine. 
Thank you for the amazing work. 
Just one quick question before i close: if i have the `googlevideo.com/videoplayback`  link from an API call and i just want to use this library for the download part, how do i proceed?

**Comment by sealedtx** [comment]
yes, indeed there is no constructor for such case
but you can create `JSONObject json` and populate it with required fields

**Comment by rajjys** [comment]
Thank you Mr. Igor and sorry for taking too much of your time. I've learned a lot from this conversation alone. Keep up the good work and stay safe.
