### ISSUE TITLE
Fail on all videos

### ISSUE THREAD

**Issue by coyote66** [sealedtx/java-youtube-downloader#19]
Hi bro, very nice work, i love it, at now fails in all videos:

W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.replace(java.lang.CharSequence, java.lang.CharSequence)' on a null object reference
 W/System.err:     at com.github.kiulian.downloader.model.formats.Format.<init>(Format.java:55)
 W/System.err:     at com.github.kiulian.downloader.model.formats.AudioVideoFormat.<init>(AudioVideoFormat.java:39)

Maby something related to Cypher ?

**Comment by AlieksieievYurii** [comment]
I have got the same problem, but I have already fixed it:)

**Comment by coyote66** [comment]
Great bro !! congratulations ! i'm waiting for new release !! many thanks !

**Comment by AlieksieievYurii** [comment]
Please see the opened issue by me: https://github.com/sealedtx/java-youtube-downloader/issues/20
There I have described the problem:)

**Comment by coyote66** [comment]
I see, many thanks bro...

**Comment by sealedtx** [comment]
@coyote66 Thank you for submitting an issue! Already resolved in #21 and I just drafted new release with this fix. Sorry for delay

**Comment by sealedtx** [comment]
Closing due to no activity from the issuer within a month
