### ISSUE TITLE
java.lang.ClassNotFoundException: com.github.kiulian.downloader.YoutubeException

### ISSUE THREAD

**Issue by oluwabajio** [sealedtx/java-youtube-downloader#25]
I have been battling with this error for a long time now. I am using maven with intellij ide ultimate

Caused by: java.lang.ClassNotFoundException: com.github.kiulian.downloader.YoutubeException
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1365)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)

**Comment by oluwabajio** [comment]
<img width="832" alt="Screen Shot 2020-07-05 at 5 36 07 AM" src="https://user-images.githubusercontent.com/13810874/86525628-8c2c6600-be81-11ea-95aa-6f33152362de.png">

**Comment by oluwabajio** [comment]
ok, i switched from maven to gradle and everything is working fine.
