### ISSUE TITLE
API 29 and above , File Save Doesnt Work!(Addition of Scoped Storage)

### ISSUE THREAD

**Issue by Shabinder** [sealedtx/java-youtube-downloader#29]
**Probable Cause:** "There was huge privacy change in android Q by introducing **Scoped Storage**."
In API level 29 direct access to shared/external storage devices is deprecated

**_.mkdirs()_** always return False!

**Error:** 
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.shabinder.musicforeveryone, PID: 7005
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915) 
    **Caused by: java.io.IOException: Could not create output directory: my_audios**
        at com.github.kiulian.downloader.model.Utils.createOutDir(Utils.java:22)
        at com.github.kiulian.downloader.model.YoutubeVideo.download(YoutubeVideo.java:160)
        at com.github.kiulian.downloader.model.YoutubeVideo.download(YoutubeVideo.java:153)
        at com.github.kiulian.downloader.model.YoutubeVideo.download(YoutubeVideo.java:149)
        at com.shabinder.musicForEveryone.fragments.MainFragment$onCreateView$3.onClick(MainFragment.kt:114)
        at android.view.View.performClick(View.java:7259)
        at android.view.View.performClickInternal(View.java:7236)
        at android.view.View.access$3600(View.java:801)
        at android.view.View$PerformClick.run(View.java:27896)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)

**Comment by sealedtx** [comment]
@Shabinder Hi, thank you for submitting the issue! May I ask you to search for solution, because I didn't follow android updates for a year and it may take a while to dive into. 
As quick fix I may suggest you adding manifest attribute as mentioned [here](https://stackoverflow.com/a/56821320)
```
<manifest ... >
  <!-- This attribute is "false" by default on apps targeting Android Q. -->
  <application android:requestLegacyExternalStorage="true" ... >
    ...
  </application>
</manifest>
```

**Comment by Shabinder** [comment]
Hey , Upon Testing on my other Device API28(PIE), getting the same error.....
Its strange..., yeah i have already enabled android:requestLegacyExternalStorage="true",
Still Getting same error on both PIE and Anroid Q ....

**Comment by sealedtx** [comment]
@Shabinder Could you please share your code snippet for downloading video?

**Comment by Shabinder** [comment]
val video = ytDownloader?.getVideo(data.id)
                val details = video?.details()

                val outputDir = File("my_audios")
                val formatByItag = video?.findFormatByItag(141)
                if (formatByItag != null) {
                    Log.i("ytDownloader", formatByItag.url())
                }else{Log.i("ytDownloader", "fortmatByItag.url() is null")}

                val file:File = video!!.download( formatByItag , outputDir)

                Log.i("YT File Path=> ", file.path)

**Comment by sealedtx** [comment]
@Shabinder I think you should modify outputDir to be more specific, because now it is relative path to the current working directory (I don't know what is cwd for android, it could be "/" which is probably blocked for writing), but you should use specific absolute path, something like this:
`val outputDir = File(Environment.getExternalStorageDirectory().toString() + File.separator + "my_audios")`
Please do experiments with output dir, and make research about: where you have access and can write on android. 
[This](https://commonsware.com/blog/2019/06/07/death-external-storage-end-saga.html) could be usefull

**Comment by Shabinder** [comment]
I will try that and report back....soon

**Comment by Shabinder** [comment]
Hey, Yup , It started Working ....
But i may suggest , implementing usage of scoped storage , in this library is gonna needed sooner or later....
Even i might try to implement Scoped Storage and new way of Saving Files, by forking this repo soon, and will send a Pull Request ... maybe in a couple Days!
Or you are gonna implemet it yourelf soon enough ,too?

Anyways, Thanks :-)

**Comment by sealedtx** [comment]
@Shabinder PR is welcomed! As I said I didn't follow android updates for a while

**Comment by xibr** [comment]
do something like this 
`File outputDir = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS), "videos");`

also don't forget add this

> <manifest ... >
> 
>  <application android:requestLegacyExternalStorage="true" ... >
>   ...

it's working on API 29 android 10.

**Comment by xibr** [comment]
Also, you can extract the link and use android download manager.

**Comment by Shabinder** [comment]
> Also, you can extract the link and use android download manager.

Thanks for Pointing this out , I will give this a try ..too

Closing The Issue For Now.
