### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by MCrissDev** [sealedtx/java-youtube-downloader#30]
Seems that Google changed again some things so the library throws an exception:

 com.github.kiulian.downloader.YoutubeException$CipherException: Transofrm object not found

Example link not working:

https://www.youtube.com/watch?v=fCZVL_8D048

**Comment by 8o8aua** [comment]
The same. It worked yesterday. Today doesn't work.
Sample video: https://www.youtube.com/watch?v=CY8E6N5Nzec

**Comment by Shabinder** [comment]
Yup stopped Working Today......

 I/YC searched for: The Spectre Alan Walker
2020-07-21 14:17:31.737 17430-17430/com.shabinder.musicforeveryone I/YC links received: **wJnBTPUQS5A**
2020-07-21 14:17:33.947 17430-17430/com.shabinder.musicforeveryone D/AndroidRuntime: Shutting down VM
2020-07-21 14:17:33.948 17430-17430/com.shabinder.musicforeveryone E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.shabinder.musicforeveryone, PID: 17430
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915) 
     **Caused by: com.github.kiulian.downloader.YoutubeException$CipherException: Transofrm object not found**
        at com.github.kiulian.downloader.cipher.CachedCipherFactory.getTransformObject(CachedCipherFactory.java:163)
        at com.github.kiulian.downloader.cipher.CachedCipherFactory.getTransformFunctionsMap(CachedCipherFactory.java:142)
        at com.github.kiulian.downloader.cipher.CachedCipherFactory.createCipher(CachedCipherFactory.java:93)
        at com.github.kiulian.downloader.parser.DefaultParser.parseFormat(DefaultParser.java:170)
        at com.github.kiulian.downloader.parser.DefaultParser.parseFormats(DefaultParser.java:126)
        at com.github.kiulian.downloader.YoutubeDownloader.getVideo(YoutubeDownloader.java:69)
        at com.shabinder.musicForEveryone.downloadHelper.DownloadHelper$DefaultImpls.downloadTrack(DownloadHelper.kt:21)
        at com.shabinder.musicForEveryone.recyclerView.TrackListAdapter.downloadTrack(TrackListAdapter.kt:17)
        at com.shabinder.musicForEveryone.recyclerView.TrackListAdapter$onBindViewHolder$1.onClick(TrackListAdapter.kt:42)
        at android.view.View.performClick(View.java:7259)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:967)
        at android.view.View.performClickInternal(View.java:7236)
        at android.view.View.access$3600(View.java:801)
        at android.view.View$PerformClick.run(View.java:27896)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)

**Comment by sealedtx** [comment]
Hi guys, you are right, I believe something has been changed in google's ciphering. Research is required. I will try to find solution, but help is welcomed

**Comment by sealedtx** [comment]
@8o8aua @Shabinder @MCrissDev check out new release and test it

**Comment by MCrissDev** [comment]
Thank you @sealedtx works like a charm on my end.

**Comment by 8o8aua** [comment]
Thank you @sealedtx . It works :)

**Comment by MCrissDev** [comment]
Closing the issue.
