### ISSUE TITLE
CipherException: Transofrm object not found

### ISSUE THREAD

**Issue by coyote66** [sealedtx/java-youtube-downloader#35]
Hi again bro !, today i have this error in some videos, this zr6HHU0fxOA for example:

 _com.github.kiulian.downloader.YoutubeException$CipherException: Transofrm object not found
		at com.github.kiulian.downloader.cipher.CachedCipherFactory.getTransformObject(CachedCipherFactory.java:163)
		at com.github.kiulian.downloader.cipher.CachedCipherFactory.getTransformFunctionsMap(CachedCipherFactory.java:142)
		at com.github.kiulian.downloader.cipher.CachedCipherFactory.createCipher(CachedCipherFactory.java:93)_

I hope you can help me, great job i love your work.

Thanks you very much.

**Comment by sealedtx** [comment]
@coyote66 Hi, please check out the latest release 2.2.2 (07.23.2020) and report if error exists. I believe your issue has been already fixed, look at #30

**Comment by coyote66** [comment]
Hi bro, i have already checked release 2.2.2, but i have same error.
Thanks.

**Comment by sealedtx** [comment]
@coyote66 just checked you videoId (zr6HHU0fxOA) and it works. Make sure you cleaned/reimport maven(gradle)/rebuild.

**Comment by sealedtx** [comment]
Closed due to no activity from issue.
