### ISSUE TITLE
can't get itag 22

### ISSUE THREAD

**Issue by bunaif** [sealedtx/java-youtube-downloader#4]
I tried to get itag 22 but i couldn't find it, you can check it

**Comment by bunaif** [comment]
and more urls not working
https://www.youtube.com/watch?v=AgFeZr5ptV8
https://www.youtube.com/watch?v=AX3Bsiq-13k
https://www.youtube.com/watch?v=A9hcJgtnm6Q
https://www.youtube.com/watch?v=AmLNlmleGV8
https://www.youtube.com/watch?v=ABZsjO36ILM
https://www.youtube.com/watch?v=As7vSu29Sh8
https://www.youtube.com/watch?v=AI94Johmqg4

**Comment by sealedtx** [comment]
@bunaif Hi, sorry for delay. I had no spare time to support this repo. The reason why your urls are not working - youtube cipher videos with copyrights, this repo currently does not support this feature. But this weekend I am going to write fixes to add support for downloading ciphered videos with signature.

**Comment by bunaif** [comment]
@sealedtx  hi,

Well, I will review the changes later

It is good that you have updated the repo. 

Thank you.

**Comment by sealedtx** [comment]
@bunaif Just released **java-youtube-downloader 2.0**, please, check it out. Will be glad to get some feedback if bugs are present

**Comment by bunaif** [comment]
@sealedtx Hi, Something is not right

`try {
            YoutubeDownloader downloader = new YoutubeDownloader();
            YoutubeVideo video = downloader.getVideo("6GC8JF2FOgA");
            VideoDetails details = video.details();
            String title = details.title();
        } catch (IOException | YoutubeException e) {
            e.printStackTrace();
        }`

error code

`java.lang.ExceptionInInitializerError
	at com.github.kiulian.downloader.YoutubeDownloader.<init>(YoutubeDownloader.java:46)
	at com.app.example.Main.onCreate(Main.java:711)
	at android.app.Activity.performCreate(Activity.java:7326)
	at android.app.Activity.performCreate(Activity.java:7317)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3235)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6986)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
Caused by: java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 27
;ytplayer\.config = (\{.*?});
                           ^
	at java.util.regex.Pattern.compileImpl(Native Method)
	at java.util.regex.Pattern.compile(Pattern.java:1344)
	at java.util.regex.Pattern.<init>(Pattern.java:1328)
	at java.util.regex.Pattern.compile(Pattern.java:950)
	at com.github.kiulian.downloader.extractor.DefaultExtractor.<clinit>(DefaultExtractor.java:37)
	... 17 more`

**Comment by sealedtx** [comment]
@bunaif looks like you are using java-youube-downloader in androip app, right? It seems like something wrong with Regex standards for android java? What java version android supports now? I will appreciate if you could do some research on this, and we will fix regex to support android ;)

**Comment by bunaif** [comment]
> looks like you are using java-youube-downloader in androip app, right?

yes.

I have been using the previous version and there is no problem.

>  It seems like something wrong with Regex standards for android java? What java version android supports now? 

I think, check this about java version https://stackoverflow.com/questions/36638657/run-android-studio-with-jre-1-8-or-later-version

**Comment by bunaif** [comment]
@sealedtx hi, now its working fine after this change [fix bug with android regex syntax](https://github.com/sealedtx/java-youtube-downloader/commit/6e3d7517e0afe2f964aee4ee95173c5fddcf7c56) 

I will check more if there is any problem. And I will give you some notesز

thank you.

**Comment by sealedtx** [comment]
@bunaif, previous version was based not on regex searching, but on string occurrence searching. I just release 2.0.1, where I also removed java 8 features to support older versions of android. Thank you for the feedback.

**Comment by bunaif** [comment]
> previous version was based not on regex searching, but on string occurrence searching.

Thanks for the clarification.

> I just released 2.0.1, where I have also removed java 8 features to support older versions of android.

Thank you so much.
