### ISSUE TITLE
Cannot load playlists

### ISSUE THREAD

**Issue by Synt4xErr0r4** [sealedtx/java-youtube-downloader#53]
Hey there!

I'm currently experiencing an issue where I'm unable to get playlist-details, because apparently for some playlists (like `OLAK5uy_kiTxC7OplYPiaW4EqzAdqmtguAY7s7f2g`) the JSON element `sidebar.playlistSidebarRenderer.items[1]` does not exist (index 0 does exists though):
> Caused by: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
    at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
    at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
    at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
    at java.base/java.util.Objects.checkIndex(Objects.java:373)
    at java.base/java.util.ArrayList.get(ArrayList.java:427)
    at fastjson@1.2.62/com.alibaba.fastjson.JSONArray.getJSONObject(JSONArray.java:241)
    at java.youtube.downloader@2.4.0/com.github.kiulian.downloader.parser.DefaultParser.getPlaylistDetails(DefaultParser.java:217)
    at java.youtube.downloader@2.4.0/com.github.kiulian.downloader.YoutubeDownloader.getPlaylist(YoutubeDownloader.java:87)
	\<my code...\>

It's this part of the code that throws the exception (at DefaultParser#getPlaylistDetails(String, JSONObject):216):
```java
JSONArray sideBarItems = initialData.getJSONObject("sidebar").getJSONObject("playlistSidebarRenderer").getJSONArray("items");
String author = sideBarItems.getJSONObject(1)
    <...>
```

Here's what I did: (this should be correct, right?)

```java
YoutubePlaylist playlist = new YoutubeDownloader().getPlaylist("OLAK5uy_kiTxC7OplYPiaW4EqzAdqmtguAY7s7f2g");
```

It worked fine with the Bruce lee playlist (`PLC3w7RzH8Yf9Zhgk43XX2w_HEDNptS-Ca`) from the [YoutubePlaylistTest](https://github.com/sealedtx/java-youtube-downloader/blob/master/src/test/java/com/github/kiulian/downloader/YoutubePlaylistTest.java).

Any idea what to do?

**Comment by sealedtx** [comment]
@Synt4xErr0r4 Hi, do you know why this playlist has no author? The code fails to retrieve author, but I can't even find it browsing webpage.

**Comment by Synt4xErr0r4** [comment]
Oh, didn't even notice that. Pretty weird. Apparently, all of [those playlists](https://www.youtube.com/c/EISBRECHERofficial/playlists?view=71&sort=dd&shelf_id=1114) have no author. Maybe they're like auto-generated or something?

**Comment by sealedtx** [comment]
@Synt4xErr0r4 Just drafted a new release 2.4.1 with patch, should works for your playlists. Try it

**Comment by Synt4xErr0r4** [comment]
Thanks! Works great now!
