### ISSUE TITLE
Can't make a working jar

### ISSUE THREAD

**Issue by dspolimi** [sealedtx/java-youtube-downloader#55]
I'm trying to use it in a personal project. I created a jar with your code but i can't make it work.

The same code works if i create a new class in your project, but if i use your project as a jar and i import that jar it doesn't.

This is the code that i'm using

**String link = "NeQM1c-XCDc";
        YoutubeDownloader youtubeDownloader = new YoutubeDownloader();
        YoutubeVideo video = null;
        File outputDir = new File(System.getProperty("user.home").concat("\\Downloads\\yt"));
        outputDir.mkdir();
        try {
            video = youtubeDownloader.getVideo(link);
        } catch (YoutubeException e) {
            e.printStackTrace();
        }
        try {
            assert video != null;
            video.download(video.audioFormats().get(0),outputDir);
        } catch (YoutubeException | IOException e) {
            e.printStackTrace();
        }**

This is the exception
`Exception in thread "main" java.lang.NoClassDefFoundError: com/alibaba/fastjson/JSON
	at com.github.kiulian.downloader.parser.DefaultParser.getPlayerConfig(DefaultParser.java:87)
	at com.github.kiulian.downloader.YoutubeDownloader.getVideo(YoutubeDownloader.java:69)
	at com.main.App.main(App.java:27)
Caused by: java.lang.ClassNotFoundException: com.alibaba.fastjson.JSON
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 3 more
`

**Comment by dspolimi** [comment]
Solved,
there were missing .class files in the jar, i've done an error creating the jar.
