### ISSUE TITLE
BadPageException: Could not parse player config json

### ISSUE THREAD

**Issue by Toles907** [sealedtx/java-youtube-downloader#62]
@sealedtx Hi.

There was an error downloading the example page below.
https://www.youtube.com/watch?v=689GoEBjMhY

```
BadPageException: Could not parse player config json
at com.github.kiulian.downloader.parser.DefaultParser.getPlayerConfig(DefaultParser.java:64)
at com.github.kiulian.downloader.YoutubeDownloader.getVideo(YoutubeDownloader.java:49)
```

I checked the html file.
```javascript
var ytplayer=window.ytplayer||{};var ytInitialPlayerResponse=window.ytInitialPlayerResponse;(function playerBootstrap(){if(ytInitialPlayerResponse){ytplayer.config={args:{raw_player_response:ytInitialPlayerResponse}};var createPlayer=window.yt&&window.yt.player&&window.yt.player.Application&&(window.yt.player.Application.createAlternate||window.yt.player.Application.create);if(createPlayer){createPlayer("player-api",ytplayer.config,ytplayer.web_player_context_config);ytplayer.config.loaded=true}}})

{args:{raw_player_response:ytInitialPlayerResponse}} // tThis is an unusual json code.
```
Normally output is in json format, but the code above is not.

```json
{"args":{"player_response":"{\"responseContext\":{\"serviceTrackingParams\":[{\"service\":\"GFEEDBACK\",\"params\":[
....
```
(Normally)

That's why I'm getting a player config json error. Is there a solution?

(I think it would be good to refer to the example I posted before.)
example1 (The top part is a bit cut off.)
https://gist.github.com/Toles907/13f743252dd50ea3a9d80a8731cf3fef

example2
https://gist.github.com/Toles907/bec6d723ec74cf91de5961616e8947ea

**Comment by kangsLee** [comment]
@Toles907 Maybe it's testing a new player on YouTube.

**Comment by Toles907** [comment]
@kangsLee Great.
