### ISSUE TITLE
Could not parse web page

### ISSUE THREAD

**Issue by poornerd** [sealedtx/java-youtube-downloader#74]
I have had this problem on several (all) of my servers that I have tested on, but locally it it works.

Could it be that YouTube is blocking server ranges on AWS or Digital Ocean?  Has anyone else experienced this?

`com.github.kiulian.downloader.YoutubeException$BadPageException: Could not parse web page
	at com.github.kiulian.downloader.extractor.DefaultExtractor.extractYtPlayerConfig(DefaultExtractor.java:78)
	at com.github.kiulian.downloader.parser.DefaultParser.getPlayerConfig(DefaultParser.java:77)
	at com.github.kiulian.downloader.YoutubeDownloader.getVideo(YoutubeDownloader.java:69)`

I upgraded to 2.5.1 - but I experienced the same behaviour from 2.4.0 as well.

**Comment by poornerd** [comment]
never mind - sorry, my deployment script had a bug
