### ISSUE TITLE
Error parsing.

### ISSUE THREAD

**Issue by yuradn** [sealedtx/java-youtube-downloader#93]
After starting parsing video info, the following errors occur:
W/System.err: Error parsing format: unknown itag 597
W/System.err: Error parsing format: unknown itag 598
W/System.err: Error parsing format: unknown itag 599
W/System.err: Error parsing format: unknown itag 600

**Comment by sealedtx** [comment]
@yuradn Hi, these are probably new youtube formats with unknown itags. Research is required

**Comment by sealedtx** [comment]
@yuradn Please, provide video link with such formats

**Comment by yuradn** [comment]
@sealedtx For example: https://www.youtube.com/watch?v=VslI_7VEhck.

**Comment by 372362092** [comment]
org.opentest4j.AssertionFailedError: 
Expected :true
Actual   :false
<Click to see difference>


	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:35)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:179)

这是咋回事

**Comment by 372362092** [comment]
VideoDetails videoDetails = parseVideoDetails(videoId, playerResponse);
到这里就报错了

**Comment by sealedtx** [comment]
@372362092 you can open new issue and describe your problem there, in English please

**Comment by 372362092** [comment]
I don't know why my connection timeout is showing here

**Comment by sealedtx** [comment]
@372362092 please open new issue and share code snippet which causes errors

**Comment by 372362092** [comment]
> @372362092请打开新问题并分享导致错误的代码片段

 
        assertDoesNotThrow(() -> {
            YoutubeProgressCallback<File> mockCallback = mock(YoutubeProgressCallback.class);
            RequestVideoFileDownload request = new RequestVideoFileDownload(format).callback(mockCallback).async();
            Response<File> responseFile = downloader.downloadVideoFile(request);

            assertTimeout(Duration.ofSeconds(5), () -> {
                assertTrue(responseFile.ok());
                File file = responseFile.data();

                validateFileDownloadAndDelete(format, file);
            });
 Code

**Comment by 372362092** [comment]
org.opentest4j.AssertionFailedError: download video async with callback should work ==> Unexpected exception thrown: java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)

	at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:83)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:54)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:41)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3154)
	at com.github.kiulian.downloader.YoutubeDownloader_Tests.downloadVideo_Success(YoutubeDownloader_Tests.java:134)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)

**Comment by sealedtx** [comment]
@372362092 this exception is not related to java-youtube-downloader sources, have a look https://stackoverflow.com/questions/41956692/could-not-initialize-plugin-interface-org-mockito-plugins-mockmaker
if you have any other problems please open SEPARATE issue, do not write here
